application:
  api_key: "c2262f44-9e96-11ea-9981-0242c0a89004"
  api_path: /api
  databases:
    default: /data/data.csv
  encryption:
    enabled: false
  logging:
    backup_count: 5
    datefmt: '%Y-%m-%d %H:%M:%S'
    file: fresh.log
    format: '%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s'
    level: DEBUG
    max_size: 1024
    use_console: true
  port: '5000'
  server_url: http://vserver
  task_dir: /mnt/tasks
environments:
  acc: {}
  dev: {}
  prod: {}
  test: {}
