version: "3"
services:
  db:
    image: postgres
    environment:
      - "POSTGRES_USER=vantage"
      - "POSTGRES_PASSWORD=vantage"
      - "POSTGRES_DB=vantage"
      - "PGDATA=/data"
    ports:
      - 5433:5432
    volumes:
      - ./pgdata:/data
#
#  migrate:
#    volumes:
#      - ./migrations:/flyway/sql/
#    image: boxfuse/flyway
#    command: migrate -url=jdbc:postgresql://db/vantage -user=vantage -password=vantage -baselineOnMigrate=true -connectRetries=60

  vserver:
    image: "harbor.vantage6.ai/infrastructure/server:latest"
    volumes:
      - ./server:/mnt/
    command: "vserver-local start -c /mnt/config.yml"
    ports:
      - "5001:5000"

  mumc:
    container_name: vantage6-mumc-user
    depends_on:
      - vserver

    image: "harbor.vantage6.ai/infrastructure/node:latest"
    command: "vnode-local start -c /mnt/config/mumc.yml --dockerized"
    volumes:
      - ./mumc-node-config.yml:/mnt/config/mumc.yml
      - ./diabetes.csv:/mnt/database/database.csv
      - /var/run/docker.sock:/var/run/docker.sock
      - shared-volume:/mnt/data
    environment:
      - DATA_VOLUME_NAME=vantage6-local-setup_shared-volume
      - DATABASE_URI=/mnt/database.csv

volumes:
  shared-volume:


#
#  registry:
#    image: registry:2
#    ports:
#      - 5001:5000
