version: "3.4"
services:
  db:
    image: postgres:15-alpine
    environment:
      - "POSTGRES_USER=vantage"
      - "POSTGRES_PASSWORD=vantage"
      - "POSTGRES_DB=vantage"
      - "PGDATA=/data"
    ports:
      - 5433:5432
    volumes:
      - ./pgdata:/data

  vserver:
    image: harbor2.vantage6.ai/infrastructure/server:cotopaxi-live
    depends_on:
      - db
    volumes:
      - ./server:/mnt/
    ports:
      - "5000:5000"
    command: ["/bin/bash", "-c", "/usr/sbin/sshd && /vantage6/vantage6-server/server.sh"]
  gui:
    image: harbor2.vantage6.ai/infrastructure/ui
    depends_on:
      - vserver
    ports:
      - "8080:80"
    environment:
      - API_URL=http://localhost:5001/api

  jupyter:
    image: jupyter/minimal-notebook:2023-03-06
    ports:
      - "8888:8888"
