version: "3.5"
services:
  db:
    image: postgres
    environment:
      - "POSTGRES_USER=vantage"
      - "POSTGRES_PASSWORD=vantage"
      - "POSTGRES_DB=vantage"
      - "PGDATA=/data"
    ports:
      - 5433:5432
    volumes:
      - ./pgdata:/data
      - ./initial_db_data:/docker-entrypoint-initdb.d

  vserver:
    image: "harbor.vantage6.ai/infrastructure/server:latest"
    depends_on:
      - db
    volumes:
      - ./server:/mnt/
    command: vserver-local start -c /mnt/config.yml
    ports:
      - "5001:5000"

  rdfstore:
    image: "jvsoest/graphdb-free:fairstation"
    ports:
      - "7200:7200"
    networks:
      - vantage6-escience-user-net

  escience:
    # We are not specifying a network, but the node container will automatically
    # connect to vantage6-escience-user-net, thereby the node and algorithm
    # container have acces to the rdf store on this network.
    container_name: vantage6-escience-user
    image: "harbor.vantage6.ai/infrastructure/node:latest"
    command: "vnode-local start -c /mnt/config/escience.yml --dockerized"
    volumes:
      - ./nodes/escience/escience-node-config.yml:/mnt/config/escience.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - escience-shared-volume:/mnt/data
    environment:
      - DATA_VOLUME_NAME=escience-shared-volume
      - DATABASE_URI=http://rdfstore:7200/repositories/repo1

volumes:
  escience-shared-volume:
    name: escience-shared-volume

networks:
  vantage6-escience-user-net:
    name: vantage6-escience-user-net
#
#  registry:
#    image: registry:2
#    ports:
#      - 5001:5000
