version: "3"
services:
  db:
    image: postgres
    environment:
      - "POSTGRES_USER=vantage"
      - "POSTGRES_PASSWORD=vantage"
      - "POSTGRES_DB=vantage"
      - "PGDATA=/data"
    ports:
      - 5433:5432
    volumes:
      - ./pgdata:/data

  vserver:
    image: "harbor.vantage6.ai/infrastructure/server:latest"
    depends_on:
      - db
    volumes:
      - ./server:/mnt/
    command: "vserver-local start -c /mnt/config.yml"
    ports:
      - "5001:5000"

  cbs:
    container_name: vantage6-cbs-user
    depends_on:
      - vserver
    build:
      context: ../vantage6-node/
    command: "vnode-local start -c /mnt/config/cbs.yml --dockerized"
    volumes:
      - ./cbs-node-config.yml:/mnt/config/cbs.yml
      - ./cbs-data.csv:/mnt/database.csv
      - /var/run/docker.sock:/var/run/docker.sock
      - shared-volume:/mnt/data
    environment:
      - DATA_VOLUME_NAME=vantage6-local-setup_shared-volume
      - DATABASE_URI=/mnt/database.csv

volumes:
  shared-volume:

#
#  registry:
#    image: registry:2
#    ports:
#      - 5001:5000
