version: "3.4"
services:
  db:
    image: postgres
    environment:
      - "POSTGRES_USER=vantage"
      - "POSTGRES_PASSWORD=vantage"
      - "POSTGRES_DB=vantage"
      - "PGDATA=/data"
    ports:
      - 5433:5432
    volumes:
      - ./pgdata:/data

  vserver:
    image: "harbor2.vantage6.ai/infrastructure/server:3.3.7"
    depends_on:
      - db
    volumes:
      - ./server:/mnt/
    command: vserver-local start -c /mnt/config.yml
    ports:
      - "5001:5000"

  gui:
    image: harbor2.vantage6.ai/infrastructure/ui
    depends_on:
      - vserver
    ports:
      - "8080:80"
    environment:
      - API_URL=http://localhost:5001/api

  jupyter:
    image: jupyter/minimal-notebook
    volumes:
      - ./jupyter/before_start.sh:/usr/local/bin/before-notebook.d/before_start.sh
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8888:8888"