version: "3.4"
services:
  db:
    image: postgres
    environment:
      - "POSTGRES_USER=vantage"
      - "POSTGRES_PASSWORD=vantage"
      - "POSTGRES_DB=vantage"
      - "PGDATA=/data"
    ports:
      - 5433:5432
    volumes:
      - ./pgdata:/data
      - ./initial_db_data:/docker-entrypoint-initdb.d

  vserver:
    image: "harbor.vantage6.ai/infrastructure/server:latest"
    depends_on:
      - db
    volumes:
      - ./server:/mnt/
    command: vserver-local start -c /mnt/config.yml
    ports:
      - "5001:5000"

  escience:
    container_name: vantage6-escience-user
    image: "harbor.vantage6.ai/infrastructure/node:latest"
    command: "vnode-local start -c /mnt/config/escience.yml --dockerized"
    volumes:
      - ./nodes/escience/escience-node-config.yml:/mnt/config/escience.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nodes/escience/boston-sample-data.ttl:/mnt/database/database.ttl
      - escience-shared-volume:/mnt/data
    environment:
      - DATA_VOLUME_NAME=escience-shared-volume
      - DATABASE_URI=/mnt/database/database.ttl


volumes:
  escience-shared-volume:
    name: escience-shared-volume

#
#  registry:
#    image: registry:2
#    ports:
#      - 5001:5000
