allow_drop_all: 'True'
api_path: /api
description: Server configuration
ip: 0.0.0.0
logging:
  backup_count: 5
  datefmt: '%Y-%m-%d %H:%M:%S'
  file: server-conf.log
  format: '%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s'
  level: DEBUG
  max_size: 1024
  use_console: true
port: '5000'
uri: postgresql://vantage:vantage@db/vantage

vpn_server:
  url: "https://vpn.carrier-mu.src.surf-hosted.nl/vpn-user-portal"
  portal_username: "vantage"
  portal_userpass: "venusvliegenvanger"
  client_id: "vantage6-server"
  client_secret: "30faa993f32"
  redirect_url: http://localhost